[package]
name = "aarch64_mutex"
version = "0.1.0"
edition = "2024"

[dependencies]
cpu = { path = "../cpu" }
mutex = { path = "../../../mutex" }

[dev-dependencies]
aarch64_unit_test = { path = "../aarch64_unit_test" }
exceptions = { path = "../exceptions" }
