[package]
name = "print"
version = "0.1.0"
edition = "2024"

[dependencies]
byte_stream = { path = "../../../byte_stream" }
typestate = { path = "../../../typestate" }
typestate_macro = { path = "../../../typestate_macro" }
mutex = { path = "../../../mutex" }
